### PR TITLE
TagBot V2

### LINKED ISSUE #28: Execution pipeline
There are a number of cases in which the webhook handler leaves a comment on a registry PR indicating something went wrong, with instructions to trigger a retry. In some of these cases (5xx from GitHub, `git` error), an automatic retry would be better.
We could take the same approach as the changelog generator, where instead of doing real work in the webhook handler, we just dump a message into SQS since it has better retry logic. In that case we just need to define which errors are retriable and which are not.

update: this is now basically a design refactor.  sqs is not really cost-effective and sns works essentially the same so the plan is to push some context message to sns topic(s) between steps. that way every step can have its own retry policy. Each step either has some side effect or 

1. webhook from github: validate and parse. keep computation minimal, since this can't retry.
2. notify: "starting", collect whatever github data will be needed (can retry, but should check for existing comments in case of retry)
3. git tag: skipped if a tag already exists, retries if necessary, absolute failure is ok too since an existing tag is not required
4. changelog generation: custom release notes are used if present,  otherwise use the generator. need the --future-release option since a release does not yet exist (i think? i don't know if a tag works without a release) failure = empty release notes + notification
5. github release: can retry, failure is actual failure
6. notify: success or failure, can retry

### PR DESCRIPTION
**Pull request by christopher-dG**
Closes #28

This is a brand new implementation of the existing TagBot functionality. It's mostly an attempt at increasing this project's bus factor (I'd wager that there are more programmers familiar with Python in the Julia community compared to Go programmers).
Some nice things:

- Much better internal retry system (no more "git: exit status 128" comments, hopefully)
- Changelogs are generated before the release is made (no more "check back in a few minutes" placeholder)
- Nothing but Python (no more Ruby code to run the changelog generator)
- Still free to deploy without a dedicated server

Feel free to look over the code and leave feedback if you like, it's mostly complete. I still have a lot of tests to write though, I probably won't get to merging/deploying this for another few weeks.

Reminder to myself: Take the time to clean up the commit log or just squash the whole thing.

september update: I'll probably get to finishing this in October

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@christopher-dG What do you think of implementing TagBot in Julia instead of Go or Python? Would that be feasible?

**Comment by christopher-dG** [comment]
When we can run Julia on Lambda, sure. But I prefer serverless for this kind of stuff.

**Comment by StefanKarpinski** [comment]
I agree that serverless is much better for this kind of use case. Otherwise someone needs to manage those servers, which is a big pain. Would pretty much only work if there's a company running them, which would probably have to be Julia Computing at this point.

**Comment by DilumAluthge** [comment]
Ahhh I didn't realize that Julia doesn't run on AWS Lambda.

I agree that this is a good use case for Serverless.

**Comment by christopher-dG** [comment]
GitHub Actions (#30) is the way forward.

Closing this with a heavy heart, because I really like this code. Admittedly, it's over-engineered as hell but it was fun :man_shrugging:.

Please don't delete this branch, since there's still some useful code for #30.

**Pull request closed without merging**
