### PR TITLE
Support self-hosted GitHub

### PR DESCRIPTION
**Pull request by christopher-dG**
Fix for #152 but not for #151 

Sorry @racinmat, I didn't realize you already had some code written 😅 

New usage for you would be to just update your TagBot.yml to add a couple of inputs

```yml
with:
  github: git.our_company.com
  github_api: git.our_company.com/api/v3
```

### CODE REVIEW

**Comment by christopher-dG** [comment]
Does a client ID + secret replace a token or is it extra?

**Comment by racinmat** [comment]
It's extra.

**Comment by racinmat** [comment]
After you merge it, I can make PR for #151, I'll use there the parameterized hostname from this PR.

**Comment by christopher-dG** [comment]
I think I have the SSH URLs figured out, sorry -- I had some code written yesterday that I didn't push. I'll merge this after CI, then feel free to add whatever you need for client ID/secret.

**Pull request merged**
