### PR TITLE
actually error on internal non-allowed error

### PR DESCRIPTION
**Pull request by IanButterworth**
Fixes https://github.com/JuliaRegistries/TagBot/issues/261

### CODE REVIEW

**Comment by IanButterworth** [comment]
Converting to draft as I'm still getting a handle on what's best to do here

**Comment by IanButterworth** [comment]
I think it's better to go with https://github.com/JuliaRegistries/TagBot/pull/277 first and see how that goes

**Comment by christopher-dG** [comment]
Just to add a bit of context to what I think confused a lot of people: this kind of successful workflow run with errors being reported elsewhere is mostly an artifact of when TagBot was supposed to be run with a cron trigger, e.g. every hour or every day. GH's default email notifications send an email for every workflow failure, so a problem with your workflow file or some other recurring error would fill up your mailbox really quick (I think Chris R had hundreds of emails in a few hours when I released a bug one time, lol).

**Comment by IanButterworth** [comment]
I'm thinking it's time to just do this (or something similar). Gone are the days of cron. I think the errors will be more manageable and actionable, and perhaps even get more eyes on helping fix remaining issues.

**Comment by IanButterworth** [comment]
@christopher-dG I'm going to go ahead and merge and release this as 1.17.0 before the end of the week. Let me know if you disagree

**Pull request merged**
