### PR TITLE
Always make annotated tags

### PR DESCRIPTION
**Pull request by christopher-dG**
[context](https://discourse.julialang.org/t/tags-created-by-tagbot-are-not-reachable/35544)

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Why not just create annotated tags by default?

**Comment by christopher-dG** [comment]
Good question, I never really thought that of that to be honest. I guess one thing I like is that when you create a lightweight tag and the referenced commit is signed, you get the nice green "Verified" next to the release too. But that's a pretty minor thing, I think only doing annotated tags would be good as well.

**Comment by DilumAluthge** [comment]
I guess the question is: suppose you use the GitHub web interface to create a new GitHub release for which the tag does not exist. GitHub will automatically create a new tag. What kind of tag does it create?

We should create the same kind of tag.

**Comment by christopher-dG** [comment]
It's lightweight.

**Comment by christopher-dG** [comment]
Thinking a bit more about it, I think it probably makes the most sense to just always make annotated tags. I like the consistency of always creating the same type of tag. And there are times where we need to annotate tags (GPG) as well as people who expect the tags to be annotated (the Discourse poster).

**Comment by DilumAluthge** [comment]
> Thinking a bit more about it, I think it probably makes the most sense to just always make annotated tags. I like the consistency of always creating the same type of tag. And there are times where we need to annotate tags (GPG) as well as people who expect the tags to be annotated (the Discourse poster).

I guess that's probably the simplest approach. Always do annotated and there is no confusion.

**Comment by DilumAluthge** [comment]
@christopher-dG Update the title of this PR?

**Pull request merged**
