### PR TITLE
Support SSH keys for pushing tags

### LINKED ISSUE #47: TagBot workflow does not trigger CI, preventing docs for tags
This is probably known, but I didn't see an issue. The problem, as @SaschaMann pointed me to, is that it's hard to get workflows to trigger other workflows. So when using Github Actions for CI and for tagbot, even adding an `on: release` trigger to the CI workflow does not cause the tagbot workflow's tag to cause CI to run (I know this because I tried just now with the repo https://github.com/ericphanson/UnbalancedOptimalTransport.jl). Hence, the docs don't get built for the tag, and one doesn't get release docs (only dev docs).

I'll switch back to the bot version of tagbot instead of the workflow (which also has the advantage of being instant instead of waiting for a tag). But maybe this issue is something to consider re #39.

### PR DESCRIPTION
**Pull request by christopher-dG**
Closes #47 
Closes #48

I haven't tested this on a real repo yet but it *should* work. I'm going on holiday so I might not get around to those tests until around Monday/Tuesday.

### CODE REVIEW

**Comment by christopher-dG** [comment]
Managed to find a bit of time, it's working as expected on my machine and I can't think of anything that would cause it to break in the Actions environment. @ericphanson or @DilumAluthge could you be my guinea pigs and try enabling this feature for any upcoming releases?

**Comment by christopher-dG** [comment]
Nope, `v1` is updated.

**Comment by ericphanson** [comment]
I tagged a patch release to test this out and try to get some stable docs; did not work out: https://github.com/ericphanson/UnbalancedOptimalTransport.jl/commit/146998c0fa5e2dd66b9d06f0e9a7865309c218a3/checks?check_suite_id=404143684

**Comment by christopher-dG** [comment]
Thanks for the report :slightly_smiling_face: That actually seems to be a random network failure... care to hit retry (or just wait 20 minutes)?

**Comment by ericphanson** [comment]
Ah, good to know! Let’s see what the next round brings then.

**Comment by christopher-dG** [comment]
Now there's a real error :slightly_smiling_face: [link](https://github.com/ericphanson/UnbalancedOptimalTransport.jl/commit/146998c0fa5e2dd66b9d06f0e9a7865309c218a3/checks?check_suite_id=404252327)

Could you set the `ACTIONS_STEP_DEBUG` secret to `true` as described [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#set-a-debug-message-debug) then retry?

**Comment by ericphanson** [comment]
Ok, I made the secret and retriggered. Gotta go for a bit but I'll be back later.

**Comment by christopher-dG** [comment]
Hm, that's puzzling. By all means it *should* be working... I'll look at this again tomorrow if I have a chance.

**Comment by ericphanson** [comment]
Ah, I think it's my fault. The documenter key is base64 encoded. I added a separate deploy key for tagbot and the corresponding secret. I'm seeing weird errors now both for tagbot and CI (`The following team project collection is stopped: S8rOy8DcAc2xRd3DTm9VCQLjdgQWYJKI4M0591MhYn7UpUtwsr. Start the collection and then try again. Administrator Reason: Creating Collection Host`) so I think that's unrelated. I'll see what happens in an hour when tagbot runs again.

**Comment by ericphanson** [comment]
Hmm, failed again with the same error... Not really sure why.

**Comment by christopher-dG** [comment]
I think I fixed it! We'll see in an hour...

**Comment by christopher-dG** [comment]
Got past the previous error and onto a new one! An "invalid key format".  Is the key secret still a base64 private key that comes out of `ssh-keygen`?

**Comment by christopher-dG** [comment]
I believe I've squashed the bug... https://serverfault.com/a/960647

**Comment by fredrikekre** [comment]
I believe that is why Documenter base64-encodes the key, to get a one-line key.

**Comment by christopher-dG** [comment]
That seems like a good idea. I added the ability to recognize those keys too so that they can be reused for TagBot.

**Comment by ericphanson** [comment]
Thanks for the fix; using the TAGBOT_KEY I added resulted in failures, but switching back to the base64-encoded DOCUMENTER_KEY and retriggering tagbot caused it to work successfully and tag the release. That in turn successfully caused github ci (due to the trigger `on: release` and the use of the ssh key, I believe) to run, which in turn caused the docs build step to trigger. Unfortunately, however, that still did not build docs for the tag i.e. the stable docs.

So I'm actually still not really sure what's needed in order to make github ci + tagbot + documenter work properly.

**Comment by christopher-dG** [comment]
The docs deployment looks like an unknown host issue with SSH (which is the exact issue that we saw first with TagBot): https://github.com/ericphanson/UnbalancedOptimalTransport.jl/runs/395589862#step:5:79

Which seems like it was mentioned in https://github.com/JuliaDocs/Documenter.jl/issues/625 but the resolution seems to be "manage your known hosts file yourself" (whereas with TagBot we chose the less secure resolution of disabling the host key check).

**Comment by ericphanson** [comment]
Thanks very much for the diagnosis :). Hmm, secure seems good but I’m not really sure how to add to the known hosts in this setting, or if they will be stable. Do you think my next step would be to ask on that documenter issue?

**Comment by christopher-dG** [comment]
This seems to be the way to go https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository#29380765

I'll try that in TagBot in a while. But yes for the Documenter part, you can ask about it there or just do the keyscan in a step before the docs.

**Comment by christopher-dG** [comment]
This seems to be the way to go https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository#29380765

I'll try that in TagBot in a while. But yes for the Documenter part, you can ask about it there or just do the keyscan in a step before the docs.

**Comment by ericphanson** [comment]
> This seems to be the way to go https://stackoverflow.com/questions/13363553/git-error-host-key-verification-failed-when-connecting-to-remote-repository#29380765
> 
> I'll try that in TagBot in a while. But yes for the Documenter part, you can ask about it there or just do the keyscan in a step before the docs.

It works! Just needed to add a `mkdir -p ~/.ssh` first to create the directory.

https://github.com/ericphanson/UnbalancedOptimalTransport.jl/blob/8585054cccb74a05a4624f1f915b9600f036eab2/.github/workflows/ci.yml#L40-L42

Finally, stable docs :). Thanks very much for the help.

**Pull request merged**
