### PR TITLE
PRs before issues in default changelog

### PR DESCRIPTION
**Pull request by fonsp**
Just a small, opinionated PR: I found the list of merged PRs much more descriptive of the changes than the list of closed issues. 

I notice this most when we closed issues without solving them, e.g. duplicates, outdated, etc. But the titles still show up in our changelog, giving the impression that they were 'solved'.

Feel free to close without discussion 🌟 it's already cool that I can use this as my custom changelog template on my own repos.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Alternatively, we could switch to using GitHub's new API for generating release notes, which only includes PRs. Personally I find the list of PRs to be sufficient.

**Comment by fonsp** [comment]
@DilumAluthge sounds great! Are you talking about [`generate_release_notes ` in the release api](https://docs.github.com/en/rest/reference/repos#create-a-release--parameters) or the unofficial [`gren`](https://github.com/github-tools/github-release-notes)? It looks like `gren` only considers issues, not PRs, but uses the `bug` or `enhancement` label to filter them, and I can't find an example output of `generate_release_notes`.

**Comment by DilumAluthge** [comment]
The official API: https://docs.github.com/en/rest/reference/repos#generate-release-notes-content-for-a-release

Looks like they give you back the release notes as a Markdown-formatted string.

**Comment by fonsp** [comment]
@DilumAluthge I updated my comment above

**Review by IanButterworth — APPROVED** [review]
@christopher-dG this seems like a good idea to me. I've independently thought it prior to this

**Pull request merged**
